repos:
-   repo: https://github.com/ambv/black
    rev: master
    hooks:
    -   id: black
-   repo: https://github.com/Lucas-C/pre-commit-hooks-bandit
    rev: master
    hooks:
    -   id: python-bandit-vulnerability-check
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: master
    hooks:
    -   id: flake8
